import { join } from "node:path";
import { expect, test } from "@playwright/test";
import { desktopShortcut, launchPackagedDesktop, makeUserDataDir, makeWorkspace, setDeferredThreadTitleMode, startThreadFromSurface } from "../helpers/electron-app";
import { pasteVisionImage, seedVisionAgentDir, startVisionHttpFixture, VISION_PNG } from "../helpers/vision-fixture";

test("packaged native Flash retains history and queued images through cancellation, retry and reopen", async ({}, info) => {
  test.skip(process.env.PI_APP_TEST_PACKAGED_NATIVE_VISION !== "1", "Explicit packaged native vision verification only.");
  test.setTimeout(120_000);
  const userData = await makeUserDataDir("packaged-native-flash-");
  const agentDir = join(userData, "agent"), workspace = await makeWorkspace("原生图片 打包验证");
  await seedVisionAgentDir(agentDir, { nativeFlash: true });
  const options = { agentDir, initialWorkspaces: [workspace], scrubProviderEnv: true, testMode: "background" as const };
  const http = await startVisionHttpFixture();
  let harness = await launchPackagedDesktop(userData, options);
  try {
    let page = await harness.firstWindow(); await http.install(harness);
    await setDeferredThreadTitleMode(harness);
    await startThreadFromSurface(page, { prompt: "Packaged native text baseline" });
    await expect(page.locator(".timeline-item--assistant")).toContainText("Primary answer from deepseek-flash");
    await page.keyboard.press(desktopShortcut(","));
    await page.getByRole("button", { name: "Models", exact: true }).click();
    const assistance = page.getByLabel("Automatic image analysis");
    await expect(assistance).toBeChecked();
    await assistance.click();
    await expect(assistance).not.toBeChecked();
    await page.getByRole("button", { name: "Back to app" }).click();
    await pasteVisionImage(page, "原生图片.png");
    await page.getByTestId("composer").fill("Read the native image"); await page.getByTestId("send").click();
    await expect(page.locator(".timeline-item--assistant")).toHaveCount(2);
    expect(JSON.stringify(http.requests[1]?.body)).toContain(`data:image/png;base64,${VISION_PNG}`);
    expect(http.requests.every((request) => request.kind === "primary" && request.body.model === "deepseek-flash")).toBe(true);
    await expect(page.getByTestId("vision-status")).toHaveCount(0);
    http.setPrimaryMode("hold");
    await page.getByTestId("composer").fill("Hold while I queue an image"); await page.getByTestId("send").click();
    await expect.poll(() => http.requests.length).toBe(3);
    await pasteVisionImage(page, "排队图片.png");
    await page.getByTestId("composer").fill("Queued native image"); await page.getByTestId("send").click();
    await expect(page.getByTestId("queued-composer-message")).toContainText("Queued native image");
    expect(http.requests).toHaveLength(3);
    http.setPrimaryMode("success"); http.release();
    await expect(page.getByTestId("queued-composer-message")).toHaveCount(0);
    await expect(page.locator(".timeline-item--assistant")).toHaveCount(4);
    expect(JSON.stringify(http.requests[3]?.body).split(VISION_PNG).length - 1).toBe(2);
    await harness.close();
    harness = await launchPackagedDesktop(userData, options); page = await harness.firstWindow(); await http.install(harness);
    await setDeferredThreadTitleMode(harness);
    await expect(page.locator(".timeline-item__attachment--image")).toHaveCount(2);
    await page.getByTestId("composer").fill("Follow up after restart"); await page.getByTestId("send").click();
    await expect.poll(() => http.requests.length).toBe(5);
    expect(http.requests.every((request) => request.kind === "primary")).toBe(true);
    expect(JSON.stringify(http.requests[4]?.body).split(VISION_PNG).length - 1).toBe(2);
    await expect(page.getByRole("button", { name: "Stop run" })).toHaveCount(0);
    http.setPrimaryMode("hold");
    await page.getByTestId("composer").fill("Cancel a native image follow-up"); await page.getByTestId("send").click();
    await expect.poll(() => http.requests.length).toBe(6);
    await page.getByRole("button", { name: "Stop run" }).click();
    await expect(page.getByRole("button", { name: "Stop run" })).toHaveCount(0);
    await expect(page.locator(".timeline-item__attachment--image")).toHaveCount(2);
    http.setPrimaryMode("success"); http.release(); http.failNextPrimary();
    await page.getByTestId("composer").fill("Read both native images after transient failure"); await page.getByTestId("send").click();
    // One local HTTP 503 exercises Pi's existing automatic retry with the same images.
    await expect.poll(() => http.requests.length).toBe(8);
    await expect(page.locator(".timeline-item--assistant").last()).toContainText("Primary answer from deepseek-flash");
    expect(http.requests.every((request) => request.kind === "primary" && request.body.model === "deepseek-flash")).toBe(true);
    for (const request of http.requests.slice(5)) expect(JSON.stringify(request.body).split(VISION_PNG).length - 1).toBe(2);
    await expect(page.getByTestId("vision-status")).toHaveCount(0);
    await page.screenshot({ path: info.outputPath("packaged-native-flash.png") });
  } finally { await harness.close(); await http.close(); }
});
